Fix lint errors in type checking
Resolves the following:
./pulp_container/app/global_access_conditions.py:23:8: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
./pulp_container/app/global_access_conditions.py:26:10: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
./pulp_container/app/global_access_conditions.py:30:10: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
Error: Process completed with exit code 1.

[noissue]

(cherry picked from commit fd749a65b42dbfaa84f40933d8edad9e2c67170a)